- name: Check for Riprap local installation
  stat:
    path: "{{ riprap_home }}/riprap/vendor"
  register: riprap

- name: Clone Riprap from Github
  git:
    repo: https://github.com/mjordan/riprap.git
    dest: "{{ riprap_home }}/riprap"
    force: yes
    version: dotenv
  when: riprap.stat.exists == False
  become: no

- name: Composer install Riprap locally
  composer:
    command: install
    working_dir: "{{ riprap_home }}/riprap"
    no_scripts: True
    no_dev: True
    optimize_autoloader: True
  ignore_errors: yes
  when: riprap.stat.exists == False
  become: no

- name: Copy islandora_config.yml for Riprap
  copy: src=islandora_config.yml dest={{ riprap_home }}/riprap/islandora_config.yml
  become: no

- name: Edit .env file
  lineinfile:
    path: "{{ riprap_home }}/riprap/.env"
    regexp: 'DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db'
    line: 'DATABASE_URL=mysql://root:islandora@127.0.0.1:3306/riprap'
  become: no

- name: Copy doctrine.yaml for MySQL
  copy: src=doctrine.yaml dest={{ riprap_home }}/riprap/config/packages/doctrine.yaml
  become: no

- name: Create Riprap database
  command: "php ./bin/console doctrine:database:create"
  args:
    chdir: "{{ riprap_home }}/riprap"

- name: Run Riprap make:migration
  command: "php ./bin/console -n make:migration"
  args:
    chdir: "{{ riprap_home }}/riprap"

- name: Run Riprap migration
  command: "php ./bin/console -n doctrine:migrations:migrate"
  args:
    chdir: "{{ riprap_home }}/riprap"

- name: Clone Islandora Riprap Drupal module from Github
  git:
    repo: https://github.com/mjordan/islandora_riprap.git
    dest: "{{ drupal_core_path }}/modules/contrib/islandora_riprap"
    force: yes
  become: no

- name: Enable Riprap module
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_riprap"

- name: Enable JSON:API module
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en jsonapi"

- name: Set Riprap mode 
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_riprap.settings riprap_mode local -y"

- name: Set Riprap local directory
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_riprap.settings riprap_local_directory {{ riprap_local_directory }} -y"

- name: Set Riprap local settings file
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_riprap.settings riprap_local_settings_file {{ riprap_local_settings_file }} -y"

- name: Set Riprap to run check_fixity via Drupal's cron
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_riprap.settings execute_riprap_in_cron 1 -y"
