- name: Check for Existing microservice
  stat:
    path: "{{ riprap_home }}/riprap/vendor"
  register: riprap

- name: Get Riprap Microservice from Github
  git:
    repo: https://github.com/mjordan/riprap.git
    dest: "{{ riprap_home }}/riprap"
    force: yes
    version: dotenv
  when: riprap.stat.exists == False
  become: no

- name: Composer Install Riprap Microservice
  composer:
    command: install
    working_dir: "{{ riprap_home }}/riprap"
  ignore_errors: yes
  when: riprap.stat.exists == False
  become: no

- name: Edit .env file
  lineinfile:
    path: "{{ riprap_home }}/riprap/.env"
    regexp: 'DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db'
    line: 'DATABASE_URL=mysql://root:islandora@127.0.0.1:3306/riprap'
  become: no

- name: Copy doctrine.yaml
  copy: src=doctrine.yaml dest={{ riprap_home }}/riprap/config/packages/doctrine.yaml

- name: Create Riprap database
  command: "php ./bin/console doctrine:database:create"
  args:
    chdir: "{{ riprap_home }}/riprap"

- name: Run Riprap make:migration
  command: "php ./bin/console -n make:migration"
  args:
    chdir: "{{ riprap_home }}/riprap"

- name: Run Riprap migration
  command: "php ./bin/console -n doctrine:migrations:migrate"
  args:
    chdir: "{{ riprap_home }}/riprap"

- name: Install Drupal Islandora Riprap module from Github
  git:
    repo: https://github.com/mjordan/islandora_riprap.git
    dest: "{{ drupal_core_path }}/modules/contrib/islandora_riprap"
    force: yes
  become: no

- name: Enable Riprap drupal module
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en islandora_riprap"

- name: Enable JSON:API module (not currently enabled by default
  command: "{{ drush_path }} --root {{ drupal_core_path }} -y en jsonapi"

- name: Set Riprap mode 
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_riprap.settings riprap_mode local -y"

- name: Set Riprap local directory
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_riprap.settings riprap_local_directory {{ riprap_local_directory }} -y"

- name: Set Riprap local settings file
  command: "{{ drush_path }} --root {{ drupal_core_path }} cset islandora_riprap.settings riprap_local_settings_file {{ riprap_local_settings_file }} -y"
